services:
  mqtt-switch-server:
    image: shellus/mqtt-switch-server
    build: .
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.yaml:/app/config.yaml
